ALTER TABLE schools
ADD COLUMN IF NOT EXISTS has_internet BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS has_smart_classroom BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS has_playground BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS has_electricity BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS smart_score INTEGER DEFAULT 0;