ALTER TABLE users
ADD COLUMN IF NOT EXISTS activation_token VARCHAR(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS otp_code VARCHAR(255) DEFAULT NULL,
ADD COLUMN IF NOT EXISTS otp_expiry TIMESTAMP DEFAULT NULL,
ADD COLUMN IF NOT EXISTS activation_expiry TIMESTAMP DEFAULT NULL,
ADD COLUMN IF NOT EXISTS is_verified BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS otp_attempts INTEGER DEFAULT 0;

-- Update existing users to be verified so they can log in
UPDATE users SET is_verified = TRUE WHERE is_verified IS NOT TRUE;
