import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import PDFDocument from "pdfkit-table";
import SVGtoPDF from "svg-to-pdfkit";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Read logo SVG
let logoSvg = null;
try {
  const logoPath = path.resolve(__dirname, "../../../frontend/public/logo/logo-icon.svg");
  if (fs.existsSync(logoPath)) {
    logoSvg = fs.readFileSync(logoPath, "utf8");
  }
} catch (error) {
  console.error("Failed to read logo-icon.svg:", error);
}

// Generate unique report ID
const generateReportId = () => {
  const dateStr = new Date().toISOString().slice(0, 10).replace(/-/g, "");
  const rand = Math.floor(100 + Math.random() * 900);
  return `RPT-${dateStr}-${rand}`;
};

// Draw standard header
const drawHeader = (doc, title, user, reportId) => {
  const startY = 40;
  
  // Draw SVG Logo
  if (logoSvg) {
    try {
      SVGtoPDF(doc, logoSvg, 40, startY, { width: 50, height: 50 });
    } catch (e) {
      console.error("Error drawing SVG logo in PDF:", e);
      // Fallback text if logo fails to render
      doc.fillColor("#0F1923").rect(40, startY, 50, 50).fill();
      doc.fillColor("#FFFFFF").fontSize(9).text("SSEVMS", 45, startY + 20, { width: 40, align: "center" });
    }
  } else {
    // Fallback badge
    doc.fillColor("#0F1923").rect(40, startY, 50, 50).fill();
    doc.fillColor("#D4A847").fontSize(9).text("SSEVMS", 45, startY + 20, { width: 40, align: "center" });
  }

  // Draw Titles
  doc.fillColor("#0F1923");
  doc.font("Helvetica-Bold").fontSize(11).text("Smart School Existence Verification & Mapping System", 105, startY);
  doc.font("Helvetica-Bold").fontSize(16).fillColor("#D4A847").text(title, 105, startY + 16);
  
  // Metadata
  const metaY = startY + 36;
  doc.font("Helvetica").fontSize(8).fillColor("#8A9BAD");
  doc.text(`Report ID: ${reportId}`, 105, metaY);
  doc.text(`Generated By: ${user.name || "System User"} (${user.role || "Operator"})`, 105, metaY + 10);
  doc.text(`Date: ${new Date().toLocaleString()}`, 105, metaY + 20);

  // Divider Line
  doc.strokeColor("#D4A847").lineWidth(1.5).moveTo(40, startY + 65).lineTo(555, startY + 65).stroke();
};

// Draw footers on all pages at the end
const drawFooters = (doc) => {
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    
    // Bottom Divider
    doc.strokeColor("#D4A847").lineWidth(0.5).moveTo(40, 800).lineTo(555, 800).stroke();

    // Footer Text
    doc.font("Helvetica-Bold").fontSize(8).fillColor("#0F1923").text("SSEVMS", 40, 808);
    doc.font("Helvetica").fontSize(8).fillColor("#8A9BAD").text("Automatically Generated Report", 150, 808, { width: 295, align: "center" });
    doc.font("Helvetica").fontSize(8).fillColor("#8A9BAD").text(`Page ${i + 1} of ${range.count}`, 450, 808, { width: 105, align: "right" });
  }
};

/**
 * Generate PDF Report
 * @param {string} reportType - summary, districts, audit, compliance, detail
 * @param {object} data - reporting query data
 * @param {object} user - user metadata
 */
export const generateReportPDF = async (reportType, data, user) => {
  const doc = new PDFDocument({ margin: 40, size: "A4", bufferPages: true });
  const reportId = generateReportId();

  // Draw header on the first page
  let reportTitle = "";
  if (reportType === "summary") reportTitle = "System Summary Report";
  else if (reportType === "districts") reportTitle = "District Performance & Compliance Report";
  else if (reportType === "audit") reportTitle = "Verification Audit Logs Report";
  else if (reportType === "compliance") reportTitle = "Smart School Compliance Checklist";
  else if (reportType === "detail") reportTitle = `School Detail Report - ${data.name || "Unknown"}`;

  // Draw Header
  drawHeader(doc, reportTitle, user, reportId);

  // Set default body position after header
  let y = 140;

  if (reportType === "summary") {
    // A. System Summary Report
    doc.fillColor("#0F1923").font("Helvetica-Bold").fontSize(12).text("Executive Summary Metrics", 40, y);
    y += 20;

    // Draw KPI Boxes
    const boxW = 110;
    const boxH = 50;
    const gap = 12;

    const metrics = [
      { label: "Total Schools", val: data.totalSchools },
      { label: "Verified", val: `${data.verifiedSchools} (${Math.round((data.verifiedSchools / (data.totalSchools || 1)) * 100)}%)` },
      { label: "Unverified", val: `${data.unverifiedSchools} (${Math.round((data.unverifiedSchools / (data.totalSchools || 1)) * 100)}%)` },
      { label: "Avg Smart Score", val: `${data.averageSmartScore} / 4.0` }
    ];

    metrics.forEach((m, idx) => {
      const bx = 40 + idx * (boxW + gap);
      doc.fillColor("#0F1923").rect(bx, y, boxW, boxH).fill();
      doc.strokeColor("#D4A847").lineWidth(1).rect(bx, y, boxW, boxH).stroke();

      doc.fillColor("#D4A847").font("Helvetica-Bold").fontSize(8).text(m.label, bx + 5, y + 8, { width: boxW - 10, align: "center" });
      doc.fillColor("#FFFFFF").font("Helvetica-Bold").fontSize(12).text(String(m.val), bx + 5, y + 24, { width: boxW - 10, align: "center" });
    });

    y += boxH + 30;

    // Infrastructure stats title
    doc.fillColor("#0F1923").font("Helvetica-Bold").fontSize(12).text("Infrastructure Compliance Statistics", 40, y);
    y += 20;

    // Setup Table for Summary
    const summaryTable = {
      headers: ["Indicator", "Count", "Percentage"],
      rows: [
        ["Internet Availability", String(data.schoolsWithInternet), `${data.internetPercentage}%`],
        ["Electricity Availability", String(data.schoolsWithElectricity), `${data.electricityPercentage}%`],
        ["Smart Classrooms", String(data.schoolsWithSmartClassroom), `${data.smartClassroomPercentage}%`],
        ["Playgrounds", String(data.schoolsWithPlayground), `${data.playgroundPercentage}%`]
      ]
    };

    doc.y = y;
    await doc.table(summaryTable, {
      width: 515,
      x: 40,
      prepareHeader: () => doc.font("Helvetica-Bold").fontSize(9).fillColor("#FFFFFF"),
      prepareRow: (row, i) => doc.font("Helvetica").fontSize(9).fillColor("#0F1923")
    });

    y = doc.y + 30;
    
    // Smart Score distribution title
    doc.fillColor("#0F1923").font("Helvetica-Bold").fontSize(12).text("Smart Score Distribution", 40, y);
    y += 20;

    const distributionTable = {
      headers: ["Smart Score", "Description", "School Count"],
      rows: [
        ["Score 4", "Full Smart Integration (Internet, Elec, Classroom, Play)", String(data.scoreDistribution.score4)],
        ["Score 3", "High Integration (3 Indicators Active)", String(data.scoreDistribution.score3)],
        ["Score 2", "Medium Integration (2 Indicators Active)", String(data.scoreDistribution.score2)],
        ["Score 1", "Low Integration (1 Indicator Active)", String(data.scoreDistribution.score1)],
        ["Score 0", "Non-digital Infrastructure (No Indicators Active)", String(data.scoreDistribution.score0)]
      ]
    };

    doc.y = y;
    await doc.table(distributionTable, {
      width: 515,
      x: 40,
      prepareHeader: () => doc.font("Helvetica-Bold").fontSize(9).fillColor("#FFFFFF"),
      prepareRow: (row, i) => doc.font("Helvetica").fontSize(9).fillColor("#0F1923")
    });

  } else if (reportType === "districts") {
    // B. District Report
    doc.fillColor("#0F1923").font("Helvetica-Bold").fontSize(12).text("District Compliance Rankings & Aggregates", 40, y);
    y += 20;

    const districtTable = {
      headers: [
        "District Name", 
        "School Count", 
        "Avg Smart Score", 
        "Verified", 
        "Unverified", 
        "Internet %", 
        "Electricity %", 
        "Smart Class %", 
        "Playground %"
      ],
      rows: data.map((d) => [
        d.district || "N/A",
        String(d.schoolCount || 0),
        String(d.averageSmartScore || 0),
        String(d.verifiedCount || 0),
        String(d.unverifiedCount || 0),
        `${d.internetPercentage || 0}%`,
        `${d.electricityPercentage || 0}%`,
        `${d.smartClassroomPercentage || 0}%`,
        `${d.playgroundPercentage || 0}%`
      ])
    };

    doc.y = y;
    await doc.table(districtTable, {
      width: 515,
      x: 40,
      prepareHeader: () => doc.font("Helvetica-Bold").fontSize(8).fillColor("#FFFFFF"),
      prepareRow: (row, i) => doc.font("Helvetica").fontSize(8).fillColor("#0F1923")
    });

  } else if (reportType === "audit") {
    // C. Verification Audit Report
    doc.fillColor("#0F1923").font("Helvetica-Bold").fontSize(12).text("Field Verification Audit Log Trail", 40, y);
    y += 20;

    const auditTable = {
      headers: ["School Name", "Verifier Name/Email", "Result", "GPS Distance (m)", "Verification Date"],
      rows: data.map((a) => [
        a.schoolName || "N/A",
        a.verifierFullName || a.verifierEmail || "N/A",
        String(a.result).toUpperCase(),
        a.distanceMeters !== null && a.distanceMeters !== undefined ? `${a.distanceMeters}m` : "N/A",
        new Date(a.timestamp).toLocaleString()
      ])
    };

    doc.y = y;
    await doc.table(auditTable, {
      width: 515,
      x: 40,
      prepareHeader: () => doc.font("Helvetica-Bold").fontSize(8).fillColor("#FFFFFF"),
      prepareRow: (row, i) => doc.font("Helvetica").fontSize(8).fillColor("#0F1923")
    });

  } else if (reportType === "compliance") {
    // D. Smart School Compliance Report
    doc.fillColor("#0F1923").font("Helvetica-Bold").fontSize(12).text("National Registry - Smart Infrastructure Compliance Checklist", 40, y);
    y += 20;

    const complianceTable = {
      headers: ["School Name", "District", "Internet", "Electricity", "Smart Class", "Playground", "Smart Score"],
      rows: data.map((s) => [
        s.name || "N/A",
        s.district || "N/A",
        s.has_internet ? "YES" : "NO",
        s.has_electricity ? "YES" : "NO",
        s.has_smart_classroom ? "YES" : "NO",
        s.has_playground ? "YES" : "NO",
        `${s.smart_score} / 4`
      ])
    };

    doc.y = y;
    await doc.table(complianceTable, {
      width: 515,
      x: 40,
      prepareHeader: () => doc.font("Helvetica-Bold").fontSize(8).fillColor("#FFFFFF"),
      prepareRow: (row, i) => doc.font("Helvetica").fontSize(8).fillColor("#0F1923")
    });

  } else if (reportType === "detail") {
    // E. School Detail Report
    doc.fillColor("#0F1923").font("Helvetica-Bold").fontSize(14).text(data.name, 40, y);
    doc.fontSize(10).fillColor("#8A9BAD").text(`District Location: ${data.district || "Unknown District"}`);
    y += 35;

    // School Profile Metadata
    doc.fillColor("#0F1923").font("Helvetica-Bold").fontSize(11).text("School Profile Metadata", 40, y);
    y += 15;

    const metadataTable = {
      headers: ["Parameter", "Detail Value"],
      rows: [
        ["School Registry ID", String(data.id)],
        ["Geographic Latitude", data.latitude !== null ? `${data.latitude}°` : "N/A"],
        ["Geographic Longitude", data.longitude !== null ? `${data.longitude}°` : "N/A"],
        ["Verification Status", String(data.status).toUpperCase()]
      ]
    };

    doc.y = y;
    await doc.table(metadataTable, {
      width: 515,
      x: 40,
      prepareHeader: () => doc.font("Helvetica-Bold").fontSize(9).fillColor("#FFFFFF"),
      prepareRow: (row, i) => doc.font("Helvetica").fontSize(9).fillColor("#0F1923")
    });

    y = doc.y + 30;

    // Compliance stats
    doc.fillColor("#0F1923").font("Helvetica-Bold").fontSize(11).text("Smart Infrastructure Status", 40, y);
    y += 15;

    const items = [
      { label: "Internet Connection", active: data.has_internet },
      { label: "Electricity Supply", active: data.has_electricity },
      { label: "Smart Classroom Equipment", active: data.has_smart_classroom },
      { label: "Outdoor Playground / Sports Field", active: data.has_playground }
    ];

    // Draw cards for indicators
    const cardW = 245;
    const cardH = 45;
    const cardGap = 15;

    items.forEach((item, idx) => {
      const col = idx % 2;
      const row = Math.floor(idx / 2);
      
      const cx = 40 + col * (cardW + cardGap);
      const cy = y + row * (cardH + cardGap);

      // Draw card box
      doc.fillColor("#141C25").rect(cx, cy, cardW, cardH).fill();
      doc.strokeColor(item.active ? "#3D7A5C" : "#C4622D").lineWidth(1.5).rect(cx, cy, cardW, cardH).stroke();

      // Card Title
      doc.fillColor("#FFFFFF").font("Helvetica-Bold").fontSize(9).text(item.label, cx + 10, cy + 12);
      
      // Status text
      doc.fillColor(item.active ? "#D4A847" : "#8A9BAD").font("Helvetica-Bold").fontSize(10).text(
        item.active ? "AVAILABLE" : "NOT AVAILABLE",
        cx + 10,
        cy + 24
      );
    });

    y += 2 * (cardH + cardGap) + 15;

    // Score display
    doc.fillColor("#0F1923").font("Helvetica-Bold").fontSize(11).text("Smart Infrastructure Score", 40, y);
    y += 15;

    // Draw score panel
    doc.fillColor("#0F1923").rect(40, y, 515, 60).fill();
    doc.strokeColor("#D4A847").lineWidth(1).rect(40, y, 515, 60).stroke();

    doc.fillColor("#D4A847").font("Helvetica-Bold").fontSize(10).text("SSEVMS COMPLIANCE RATING SCORE", 55, y + 15);
    doc.fillColor("#FFFFFF").font("Helvetica-Bold").fontSize(20).text(`${data.smart_score} / 4`, 55, y + 30);
    
    // Draw rating description
    let desc = "";
    if (data.smart_score === 4) desc = "Platinum Compliance Status: Exceptional digital education environment.";
    else if (data.smart_score === 3) desc = "Gold Compliance Status: High infrastructure readiness.";
    else if (data.smart_score === 2) desc = "Silver Compliance Status: Moderate digital infrastructure integration.";
    else if (data.smart_score === 1) desc = "Bronze Compliance Status: Basic digital components available.";
    else desc = "Legacy Status: Requires emergency infrastructure deployment.";

    doc.fillColor("#8A9BAD").font("Helvetica").fontSize(9).text(desc, 180, y + 35, { width: 350, align: "right" });
  }

  // Draw Footers dynamically on all buffered pages
  drawFooters(doc);

  // Return generated doc
  doc.end();
  return doc;
};
